version: '2'

volumes:
    dbdata:
        driver: local

services:
    leveroshost:
        image: leveros/leveroshost:latest
        container_name: leveroshost
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:z
            - ${LEVEROS_REPO_DIR}:/leveros/custcodetree:Z
        ports:
            - ${LEVEROS_LISTEN_IP_PORT}:8080
            - 127.0.0.1:6514:6514  # Dev logger.
        command: >-
            --config leveroshost
            --service leveroshost
            --containerName leveroshost
            --leverutil.leverCodeHostDir ${LEVEROS_REPO_DIR}
            --leverutil.disableRemoveContainer true
        environment:
            LEVEROS_LISTEN_IP_PORT: ${LEVEROS_LISTEN_IP_PORT}

    consul:
        image: leveros/consul:latest
        container_name: leverosconsul
        hostname: leverosconsul
        command: "-bootstrap -server"

    aerospike:
        image: leveros/aerospikedev:latest
        container_name: leverosaerospike
        hostname: leverosaerospike
        volumes:
            - dbdata:/leveros/dbdata:Z
